weather/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path,include
from web.views import *
from web import views

urlpatterns = [
    url('admin/', admin.site.urls),
    path('',index),
    path('bd_write/bd_write.html',bd_list),
    path('index/', index),
    path('indexin/', indexin),
    path('weather/', weather),
    path('register/',register),
    path('web/',include('web.urls',namespace="user")),
    path('login/',login),
    path('bd_list/',bd_list, name='bd_list'),
    path('bd_write/',bd_write),
    path('intro/',intro),
    path('logout/',logout, name='logout'),
    path('',home),
    path('board/', board, name='board'),
    path('edit/<int:pk>', boardEdit, name='edit'),
    path('delete/<int:pk>', boardDelete, name='delete'),
]

web/urls.py
from django.urls import path
from . import views
from .views import *
app_name = 'user'
urlpatterns =[
    path('', board, name='board'),
    path('register/',views.register, name='register'),
    path('index/login/', views.login, name='login'),
    path('index/logout/', views.logout, name='logout'),
    path('edit/<int:pk>', boardEdit, name='edit'),
    path('delete/<int:pk>', boardDelete, name='delete'),
]

web/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

class User(models.Model):
    user_id = models.CharField(max_length=30)
    pwd = models.CharField(max_length=20)
    name = models.CharField(max_length=10)
    gender = models.CharField(max_length=6)
    addr = models.CharField(max_length=100)
    birth = models.IntegerField(default=0,validators=[MaxValueValidator(99999999),MinValueValidator(10000000)])
    email = models.CharField(max_length=20)

    def __str__(self):
        return self.name

class Board(models.Model):
    title = models.CharField(max_length=20, null = True)
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.DO_NOTHING, null = True)
# Create your models here.

web/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User
from .models import *



class BoardForm(ModelForm):
    class Meta:
        model = Board
        fields = ['title','content']

web/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,redirect
from .models import *
from .forms import *
from django.contrib import auth
from django.contrib.auth import authenticate
from django.http import HttpResponse
from django.contrib.auth.hashers import check_password , make_password


def index(request):
    return render(request,"index.html")

def indexin(request):
    return render(request,"indexin.html")

def weather(request):
    return render(request,"weather.html")

def register(request):
    if request.method == 'POST':
        if request.POST['pw'] == request.POST['pw-confirm']:
            user = User (
                        user_id=request.POST['id'],
                        pwd=request.POST['pw'],
                        name=request.POST['name'],
                        gender=request.POST['gender'],
                        addr=request.POST['addr'],
                        birth=request.POST['birth'],
                        email=request.POST['email'],
                        )
            user.save()
            return redirect('/')
        return render(request, 'register.html')
    return render(request, 'register.html')

def login(request):
    response_data = {}

    if request.method == "GET" :
        return render(request, 'login.html')

    elif request.method == "POST":
        login_username = request.POST.get('user_id')
        login_password = request.POST.get('pwd')

        if not (login_username and login_password):
            response_data['error']="아이디와 비밀번호를 모두 입력해주세요."
        else:
            user = User.objects.get(user_id=login_username)
            upwd = user.pwd
            checkpwd = login_password
            if (upwd == checkpwd):
                print(upwd, checkpwd)
                request.session['user'] = user.id 
                #세션도 딕셔너리 변수 사용과 똑같이 사용하면 된다.
                #세션 user라는 key에 방금 로그인한 id를 저장한것.
                return render(request, 'indexin.html',response_data)
            else:
                response_data['error'] = "비밀번호를 틀렸습니다."


    return redirect('/')

def logout(request):
    if request.session.get('user'):
        del(request.session['user'])

    return redirect('/')

def home(request):
    user_id = request.session.get('user')
    if user_id :
        user_info = User.objects.get(pk=user_id)
        return HttpResponse(user_info.user_id)
    
    return HttpResponse('로그인을 해주세요')

def board(request):
    if request.method == 'POST':
        title = request.POST['title']
        content = request.POST['contents']
        user = request.user
        board = Board(
            title=title,
            content=content,
            user=user,
        )
        board.save()
        return redirect('board')
    else:
        boardForm = BoardForm
        board = Board.objects.all()
        context = {
            'boardForm' : boardForm,
            'board': board,
        }

        return render(request, 'board.html', context)

def boardEdit(request, pk):
    board = Board.objects.get(id=pk)
    if request.method == "POST":
        board.title = request.POST['title']
        board.content = request.POST['content']
        board.writer = request.user

        board.save()
        return redirect('board')

    else:
        boardForm = BoardForm
        return render(request, 'update.html',{'boardForm':boardForm})

def boardDelete(request, pk):
    board = Board.objects.get(id=pk)
    board.delete()
    return redirect('board')

def bd_write(request):
    if request.method == 'POST':
        title = request.POST['title']
        content = request.POST['content']
        board = Board(
            title=title,
            content=content,
        )
        board.save()
        return redirect('bd_write.html')

    else :
        boardForm = BoardForm
        board = Board.objects.all()
        context = {
            'boardForm' : boardForm,
                'board': board,
            }

    return render(request, 'bd_write.html', context)

def intro(request):
    return render(request,'intro.html')

def bd_list(request):
    board = Board.objects.all()
    context = {'board':board}

    return render(request, 'bd_list.html',context)

web/templates/base.html
 <!DOCTYPE html>
<html>
{% include 'head.html' %}
<body>
{% block content %}

{% endblock %}
</body>
</html>

web/templates/bd_list.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>목록</title>
    <link rel="stylesheet" href="{% static '/css/style.board.css' %}">
    <link rel="stylesheet" href="{% static '/css/media.css' %}">
    <link href="{% static '/css/bootstrap.css' %}" rel="stylesheet" />
	<link href="{% static '/css/coming-sssoon.css' %}" rel="stylesheet" /> 
    
    <!--     Fonts     -->
    <link href="{% static '/css/font-awesome.css' %}" rel="stylesheet">
    <style>
        #report1 {
      background-image: url("/static/images/style.jpg");
    }
    </style>
</head>
<body>
    <nav class="navbar navbar-transparent navbar-fixed-top" role="navigation">  
        <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
      
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <!--<ul class="nav navbar-nav">
              <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> 
                      <img src="images/flags/US.png"/>
                      English(US) 
                      <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><a href="#"><img src="images/flags/DE.png"/> Deutsch</a></li>
                      <li><a href="#"><img src="images/flags/GB.png"/> English(UK)</a></li>
                      <li><a href="#"><img src="images/flags/FR.png"/> Français</a></li>
                      <li><a href="#"><img src="images/flags/RO.png"/> Română</a></li>
                      <li><a href="#"><img src="images/flags/IT.png"/> Italiano</a></li>
                      
                      <li class="divider"></li>
                      <li><a href="#"><img src="images/flags/ES.png"/> Español <span class="label label-default">soon</span></a></li>
                      <li><a href="#"><img src="images/flags/BR.png"/> Português <span class="label label-default">soon</span></a></li>
                      <li><a href="#"><img src="images/flags/JP.png"/> 日本語 <span class="label label-default">soon</span></a></li>
                      <li><a href="#"><img src="images/flags/TR.png"/> Türkçe <span class="label label-default">soon</span></a></li>
                   
                    </ul>
              </li>
            
            </ul>-->
            <ul class="nav navbar-nav navbar-right">
                  <!--<li>
                      <a href="#"> 
                          <i class="fa fa-facebook-square"></i>
                          Join
                      </a>
                  </li>-->
                  <li>
                    <a href="/indexin">
                        <i class="joinform"></i>
                        Home
                    </a>
                </li>
                <li>
                    <a href="/login"> 
                      <i class="signupform"></i>
                      Log out
                  </a>
                </li>
             </ul>
            
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container -->
      </nav>
      <div class="main" id="report1">
      
    <div class="board_wrap">
        <div class="board_title">
            <strong>자유게시판</strong>
            <p>원하는 게시글을 올리실 수 있습니다.</p>
        </div>
        <div class="board_list_wrap">
            <div class="board_list">
                <div class="top">
                    <thead>
                    <tr>
                        <div class="num">번호</div>
                        <div class="date">제목</div>
                        <div class="title">내용</div>
                    </tr>
                    </thead>
                </div>
                {% for i in board %}
                <tbody>
                <tr>
                    <div>
                        <div class="num"><td>{{ i.id }}</td></div>
                        <div class="date"><td>{{ i.title }}</td></div>
                        <div class="title"><td>{{ i.content }}</td></div>
                    </div>
                </tr>
                </tbody>
                {% endfor %}
            </div>
            <div class="board_page">
            {% csrf_token %}
            </div>
            <div class="bt_wrap">
                <a href="http://mysite.com:8000/bd_write/" class="on">등록</a>
                <!--<a href="#">수정</a>-->
            </div>
        </div>
    </div>
</body>
</html> 

web/templates/bd_write.html
<!doctype html>
{% load bootstrap4 %}
<html lang="en">
    {% load static %}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>목록</title>
        <link rel="stylesheet" href="{% static '/css/style.board.css' %}">
        <link rel="stylesheet" href="{% static '/css/media.css' %}">
        <link href="{% static '/css/bootstrap.css' %}" rel="stylesheet" />
        <link href="{% static '/css/coming-sssoon.css' %}" rel="stylesheet" />     
        
        <!--     Fonts     -->
        <link href="{% static '/css/font-awesome.css' %}" rel="stylesheet">
</head>

<body>
<nav class="navbar navbar-transparent navbar-fixed-top" role="navigation">  
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <!--<ul class="nav navbar-nav">
        <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"> 
                <img src="images/flags/US.png"/>
                English(US) 
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><a href="#"><img src="images/flags/DE.png"/> Deutsch</a></li>
                <li><a href="#"><img src="images/flags/GB.png"/> English(UK)</a></li>
                <li><a href="#"><img src="images/flags/FR.png"/> Français</a></li>
                <li><a href="#"><img src="images/flags/RO.png"/> Română</a></li>
                <li><a href="#"><img src="images/flags/IT.png"/> Italiano</a></li>
                
                <li class="divider"></li>
                <li><a href="#"><img src="images/flags/ES.png"/> Español <span class="label label-default">soon</span></a></li>
                <li><a href="#"><img src="images/flags/BR.png"/> Português <span class="label label-default">soon</span></a></li>
                <li><a href="#"><img src="images/flags/JP.png"/> 日本語 <span class="label label-default">soon</span></a></li>
                <li><a href="#"><img src="images/flags/TR.png"/> Türkçe <span class="label label-default">soon</span></a></li>
             
              </ul>
        </li>
      
      </ul>-->
      <ul class="nav navbar-nav navbar-right">
            <!--<li>
                <a href="#"> 
                    <i class="fa fa-facebook-square"></i>
                    Join
                </a>
            </li>-->
            <li>
                <a href="http://mysite.com:8000/indexin/"> 
                    <i class="joinform"></i>
                    Home
                </a>
            </li>
            <li>
                <a href="http://mysite.com:8000/bd_list/"> 
                    <i class="joinform"></i>
                    Board
                </a>
            </li>
       </ul>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>
    <div class="main" style="background-image: url('/static/images/style.jpg')">

<!--    Change the image source '/images/default.jpg' with your favorite image.     -->
    
     
<!--   You can change the black color for the filter with those colors: blue, green, red, orange       -->

<div class="board_wrap">
    <div class="board_title">
        <strong>자유게시판</strong>
        <p>원하는 게시글을 올리실 수 있습니다.</p>
    </div>
    <div class="board_write_wrap">
        <div class="board_write">
            <form action="" method="POST" style="max-width:500px; margin:4rem;">
            {% csrf_token %}
            {% bootstrap_form boardForm %}
        </div>
        <div class="bt_wrap">
            <button type="submit" class="btn btn-primary rounded-pill col-12" href="http://mysite.com:8000/bd_list/">작성</button>
        </form>
        </div>
    </div>
</div>
 </body>
</html>

web/templates/index.html
<!doctype html>
<html lang="en">
  {% load static %}
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    
    <title>Style by Weather</title>
    <script src="{% static '/js/page_move.js' %}"></script>
    <link href="{% static '/css/bootstrap.css' %}" rel="stylesheet" />
	  <link href="{% static '/css/coming-sssoon.css' %}" rel="stylesheet" />    
    
    <!--     Fonts     -->
    <link href="{% static '/css/font-awesome.css' %}" rel="stylesheet">
  <style>
    #report1 {
      background-image: url("/static/images/style.jpg");
    }

    #report2 {
        width:100px;
        margin:auto;
        display:block;
    }

  </style>
</head>

<body>
<nav class="navbar navbar-transparent navbar-fixed-top" role="navigation">  
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <!-- <ul class="nav navbar-nav">
        <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"> 
                <img src="images/flags/US.png"/>
                English(US) 
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><a href="#"><img src="images/flags/DE.png"/> Deutsch</a></li>
                <li><a href="#"><img src="images/flags/GB.png"/> English(UK)</a></li>
                <li><a href="#"><img src="images/flags/FR.png"/> Français</a></li>
                <li><a href="#"><img src="images/flags/RO.png"/> Română</a></li>
                <li><a href="#"><img src="images/flags/IT.png"/> Italiano</a></li>
                
                <li class="divider"></li>
                <li><a href="#"><img src="images/flags/ES.png"/> Español <span class="label label-default">soon</span></a></li>
                <li><a href="#"><img src="images/flags/BR.png"/> Português <span class="label label-default">soon</span></a></li>
                <li><a href="#"><img src="images/flags/JP.png"/> 日本語 <span class="label label-default">soon</span></a></li>
                <li><a href="#"><img src="images/flags/TR.png"/> Türkçe <span class="label label-default">soon</span></a></li>
             
              </ul>
        </li>
      
      </ul> -->
      <ul class="nav navbar-nav navbar-right">
            <!--<li>
                <a href="#"> 
                    <i class="fa fa-facebook-square"></i>
                    Join
                </a>
            </li>-->
             <li>
                <a href="/login"> 
                    <i class="loginform"></i>
                    Login
                </a>
            </li>
            <li>
              <a href="{% url 'user:register' %}">
                  <i class="loginform"></i>
                  Sign Up
              </a>
          </li>
       </ul>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>
<div class="main" id="report1">

<!--    Change the image source '/images/default.jpg' with your favorite image.     -->
    
   
     
<!--   You can change the black color for the filter with those colors: blue, green, red, orange       -->

    <div class="container">
        <h1 class="logo cursive">
            <div>Style </div>
            <div>by </div>
            <div></div>Weather
        </h1>
<!--  H1 can have 2 designs: "logo" and "logo cursive"           -->
        
        <div class="content">
            <div class="subscribe">
                <h5 class="info-text">
                    Where are you going to trip?  
                </h5>
                <div class="row">
                    <div class="col-md-4 col-md-offset-4 col-sm6-6 col-sm-offset-4 " style="margin-left: 440px;">
                        <form class="form-inline" role="form" >
                          <div class="form-group">
                            <label class="sr-only" for="exampleInputEmail2">location</label>
                            <input type="text" class="form-control transparent" id="city" placeholder="Put a city name..">
                            <br><br>
                            <label class="sr-only" for="exampleInputEmail2">gender</label>
                            <select name="gender" class="form-control transparent"  id="gender">
                              <option value="male" style="color : black">Male</option>
                              <option value="female" style="color : black">Female</option>
                            </select>
                          </div>
                    </div>
                          <div class="col-md-4 col-md-offset-4 col-sm6-6 col-sm-offset-4 ">
                          <br><br>
                          <button type="button" class="btn btn-danger btn-fill" onclick="input()" id="report2" >Notify Me</button></a>
                          </div>
                </div>
                        </form>
            </div>
        </div>
            </div>
      </div>
    
 </div>
 </body>

</html>

web/templates/indexin.html
<!doctype html>
<html lang="en">
  {% load static %}
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    
    <title>Style by Weather</title>
    <script src="{% static '/js/page_move.js' %}"></script>
    <link href="{% static '/css/bootstrap.css' %}" rel="stylesheet" />
	  <link href="{% static '/css/coming-sssoon.css' %}" rel="stylesheet" />    
    
    <!--     Fonts     -->
    <link href="{% static '/css/font-awesome.css' %}" rel="stylesheet">
  <style>
    #report1 {
      background-image: url("/static/images/style.jpg");
    }
  </style>
</head>

<body>
<nav class="navbar navbar-transparent navbar-fixed-top" role="navigation">  
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <!--<ul class="nav navbar-nav">
        <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"> 
                <img src="images/flags/US.png"/>
                English(US) 
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><a href="#"><img src="images/flags/DE.png"/> Deutsch</a></li>
                <li><a href="#"><img src="images/flags/GB.png"/> English(UK)</a></li>
                <li><a href="#"><img src="images/flags/FR.png"/> Français</a></li>
                <li><a href="#"><img src="images/flags/RO.png"/> Română</a></li>
                <li><a href="#"><img src="images/flags/IT.png"/> Italiano</a></li>
                
                <li class="divider"></li>
                <li><a href="#"><img src="images/flags/ES.png"/> Español <span class="label label-default">soon</span></a></li>
                <li><a href="#"><img src="images/flags/BR.png"/> Português <span class="label label-default">soon</span></a></li>
                <li><a href="#"><img src="images/flags/JP.png"/> 日本語 <span class="label label-default">soon</span></a></li>
                <li><a href="#"><img src="images/flags/TR.png"/> Türkçe <span class="label label-default">soon</span></a></li>
             
              </ul>
        </li>
      
      </ul>-->
      <ul class="nav navbar-nav navbar-right">
            <!--<li>
                <a href="#"> 
                    <i class="fa fa-facebook-square"></i>
                    Join
                </a>
            </li>-->
             <li>
                <a href="{% url 'bd_list' %}"> 
                    <i class="joinform"></i>
                    Board
                </a>
            </li>
            <li>
              <a href="{% url 'logout' %}"> 
                  <i class="loginform"></i>
                  Log out 
              </a>
          </li>
            <li>
              <a href="{% url 'user:register' %}">
                  <i class="loginform"></i>
                  Sign Up
              </a>
          </li>
       </ul>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>
<div class="main" id="report1">

<!--    Change the image source '/images/default.jpg' with your favorite image.     -->
    
   
     
<!--   You can change the black color for the filter with those colors: blue, green, red, orange       -->

    <div class="container">
        <h1 class="logo cursive">
            <div>Style </div>
            <div>by </div>
            <div></div>Weather
        </h1>
<!--  H1 can have 2 designs: "logo" and "logo cursive"           -->
        
        <div class="content">
            <div class="subscribe">
                <h5 class="info-text">
                    Where are you going to trip?  
                </h5>
                <div class="row">
                    <div class="col-md-4 col-md-offset-4 col-sm6-6 col-sm-offset-3 ">
                      <form class="form-inline" role="form" >
                        <div class="form-group">
                          <label class="sr-only" for="exampleInputEmail2">location</label>
                          <input type="text" class="form-control transparent" id="city" placeholder="Put a city name..">
                          <br><br>
                          <label class="sr-only" for="exampleInputEmail2">gender</label>
                          <select name="gender" class="form-control transparent"  id="gender">
                            <option value="male">Male</option>
                            <option value="female">Female</option>
                          </select>
                        </div>
                        <br><br>
                        <button type="button" class="btn btn-danger btn-fill" onclick="input()" id="report2" >Notify Me</button></a>
                      </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
 </div>
 </body>

</html>

web/templates/login.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    
    <!--     Fonts     -->
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Grand+Hotel' rel='stylesheet' type='text/css'>

    <script src="{% static '/js/page_move.js' %}"></script>
    <link href="{% static '/css/bootstrap.css' %}" rel="stylesheet" />
	  <link href="{% static '/css/login.css' %}" rel="stylesheet" />   
    
  </head>
  <body>
    <nav class="navbar navbar-transparent navbar-fixed-top" role="navigation">  
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
    
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <!--<ul class="nav navbar-nav">
            <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"> 
                    <img src="images/flags/US.png"/>
                    English(US) 
                    <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li><a href="#"><img src="images/flags/DE.png"/> Deutsch</a></li>
                    <li><a href="#"><img src="images/flags/GB.png"/> English(UK)</a></li>
                    <li><a href="#"><img src="images/flags/FR.png"/> Français</a></li>
                    <li><a href="#"><img src="images/flags/RO.png"/> Română</a></li>
                    <li><a href="#"><img src="images/flags/IT.png"/> Italiano</a></li>
                    
                    <li class="divider"></li>
                    <li><a href="#"><img src="images/flags/ES.png"/> Español <span class="label label-default">soon</span></a></li>
                    <li><a href="#"><img src="images/flags/BR.png"/> Português <span class="label label-default">soon</span></a></li>
                    <li><a href="#"><img src="images/flags/JP.png"/> 日本語 <span class="label label-default">soon</span></a></li>
                    <li><a href="#"><img src="images/flags/TR.png"/> Türkçe <span class="label label-default">soon</span></a></li>
                 
                  </ul>
            </li>
          
          </ul>-->
          <ul class="nav navbar-nav navbar-right">
                <!--<li>
                    <a href="#"> 
                        <i class="fa fa-facebook-square"></i>
                        Join
                    </a>
                </li>-->
                 <li>
                    <a href="{% url 'user:register' %}">
                        <i class="joinform"></i>
                        Sign Up
                    </a>
                </li>
                 <li>
                    <a href="/index"> 
                        <i class="loginform"></i>
                        Home
                    </a>
                </li>
           </ul>
          
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container -->
    </nav>
    
    <section class="login-form">
      <h1 class="logo cursive">
        <div>Login in</div>

    </h1>
    

      <form method="POST">
        {% csrf_token %}
        <div class = "int-area">
          <input type="text" name="user_id" id="user_id"
          autocomplete="off" required>
          <label for="id">ID</label>
        </div>

        <div class="int-area">
          <input type="password" name="pwd" id="pwd"
          autocomplete="off" required>
          <label for="pw">PW</label>
        </div>

        <div class="btn-area">
          <button type = "submit" value="login">LOGIN</button>
        </div>

      </form>
      <div class="caption">
        <a href="{% url 'user:register' %}">Sign Up</a>
      </div>

    </section>
    <div class="cover black" data-color="black"></div>
  </body>
</html>